name: Build and Package Stream Deck Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Validate and Package Stream Deck Plugin
        uses: neilenns/streamdeck-cli-pack@v1
        with:
          path: com.promofaux.razer-battery-monitor.sdPlugin
          outputPath: dist

      - name: Upload packaged plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamdeck-plugin
          path: ./dist/*.streamDeckPlugin
